# Generated by Django 6.1.1 on 2026-09-27 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste', '0002_wastematerial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collection-request',
            },
        ),
        migrations.CreateModel(
            name='CollectionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_collection.collectionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('g', 'Gram'), ('l', 'Liter'), ('pc', 'Piece')], max_length=5)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reward_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collection_request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='waste_collection.collectionrequest')),
                ('waste_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste.wastecategory')),
            ],
            options={
                'db_table': 'collection-item',
            },
        ),
    ]
