# Generated by Django 6.1.1 on 2026-09-20 16:03

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.CustomManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='alternate_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reward_points',
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reward_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
