# Generated by Django 6.1.1 on 2026-09-24 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('g', 'Gram'), ('l', 'Liter'), ('pc', 'Piece')], max_length=5)),
                ('estimated_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='waste.wastecategory')),
            ],
            options={
                'db_table': 'waste-material',
            },
        ),
    ]
